import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { Suspense } from "react";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./auth/auth";

const poppins = Poppins({ subsets: ["latin"],
  weight:['100','300','400','500']
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
        <NavBar/>
        <Suspense fallback = {<div className='p-10 justify-center flex w-full'><div className="h-10 loading loading-infinity loading-lg"></div></div>}>
        <main className="p-5">
        {children}
        </main>
        </Suspense>
        </AuthProvider>
        
      </body>
    </html>
  );
}
